# Generated by Django 5.2.7 on 2025-10-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('lb', 'per lb'), ('kg', 'per kg'), ('pcs', 'per piece'), ('bag', 'per bag'), ('box', 'per box'), ('gallon', 'per gallon'), ('liter', 'per liter'), ('dozen', 'per dozen'), ('loaf', 'per loaf'), ('block', 'per block'), ('cup', 'per cup'), ('', 'each')], default='', max_length=10),
        ),
    ]
