# Generated by Django 5.2.7 on 2025-10-15 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deal_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Off'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Deal')], default='percentage', max_length=20)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Percentage discount (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount discount', max_digits=10)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='deals/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='deals', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
