# Generated by Django 5.2.7 on 2025-10-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category_alter_product_image_order'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_product_d800fc_idx',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'created_at'], name='reviews_rev_product_847b15_idx'),
        ),
    ]
